# for local development
version: '3.7'
services:
  vue:
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '8088:8080'
    volumes:
    - '.:/app'
    command: /bin/sh -c "yarn serve"
